services:
  postgres:
    image: postgres:16
    restart: always
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    networks: ["club_network"]
networks:
  club_network: {}
volumes:
  database:
