export const enum Commands {
  Events = "Мероприятия",
  CreateEvent = "Создать мероприятие",
  EventsSetPage = "EventsSetPage",
  EventsManage = "EventsManage",
  DeleteEvent = "DeleteEvent",
  ShowUsersOnEvent = "ShowUsersOnEvent",
  RegisterToEvent = "RegisterToEvent",
  RegisteredEvents = "Мои записи",
  DeleteRegistrationToEvent = "DeleteRegisterToEvent",
  Users = "Пользователи",
  MakePayers = "Добавить платников",
  RemovePayers = "Убрать платников",
  Homeworks = "Домашние задания",
  CreateHomework = "Создать ДЗ",
  HomeworksManage = "HomeworksManage",
  ShowHomework = "ShowHomework",
  HomeworksSetPage = "HomeworksSetPage",
  SendAnswerHomework = "SendAnswerHomework",
  LinkTypeHomework = "Только ссылки",
  FileTypeHomework = "Только файлы",
  DeleteHomework = "Удалить"
}
