export const enum Commands {
  Events = "Мероприятия",
  CreateEvent = "Создать мероприятие",
  EventsSetPage = "EventsSetPage",
  EventsManage = "EventsManage",
  DeleteEvent = "DeleteEvent",
  ShowUsersOnEvent = "ShowUsersOnEvent",
  RegisterToEvent = "RegisterToEvent",
  RegisteredEvents = "Мои записи",
  DeleteRegistrationToEvent = "DeleteRegisterToEvent",
  Users = "Пользователи",
  MakePayers = "Добавить платников",
  DeletePayers = "Удалить платников",
  HomeWorks = "Домашние задания",
  CreateHomeWork = "Создать ДЗ",
  HomeWorksManage = "HomeWorksManage",
  ShowHomeWork = "ShowHomeWork",
  HomeWorksSetPage = "HomeWorksSetPage",
  SendAnswerHomeWork = "SendAnswerHomeWork",
  LinkTypeHomeWork = "Только ссылки",
  FileTypeHomeWork = "Только файлы",
}
